README.md
package-lock.json
package.json

Cambie la versión vita, sacando 2 vulnerabilidades moderadas

Primer commit de mati

---

src/components/showData.tsx

se ha realizado los cambios correspondientes en el archivo show data para mostrar los datos

correcion del archivo show data para mostrar datos

---

src/components/botoneventos.tsx
src/hooks/GetCalendario.ts

- 🛠️ Creación de un componente en TSX para el botón
- 🗓️ Implementación de la lógica en TS para la obtención de datos del calendario de Google
- 🔌 Adición de función para interactuar con la API

Botón de evento con conexión a calendario

---

src/screens/Login/loginUsuario.module.css
src/screens/Login/loginUsuario.tsx

[+] 🔑 Se creó el inicio de sesión responsiva

Creacion de inicio de sesion responsive

---

src/components/Footer.tsx

[+] Arreglo en el mención de Height

Cambio a Footer

---

src/App.tsx
src/components/Footer.tsx
src/components/botoneventos.tsx

Correcciones

---

src/interfaces/Accesibilidad.ts
src/interfaces/Accesibilidad_Marcador.ts
src/interfaces/Accesibilidad_Solicitud.ts
src/interfaces/Busqueda.ts
src/interfaces/Busquedas.ts
src/interfaces/Discapacidad.ts
src/interfaces/Horario.ts
src/interfaces/Horarios.ts
src/interfaces/Marcador.ts
src/interfaces/Registro_Logs.ts
src/interfaces/Resena.ts
src/interfaces/Resenas.ts
src/interfaces/Solicitud.ts
src/interfaces/Solicitudes.ts
src/interfaces/Tipo_Recinto.ts
src/interfaces/Usuarios.ts

El script enviado también se hicieron algunos cambios, para que los datos estén en sincronización

Se realizaron los cambios de la base de datos con los mismos nombres

---

package-lock.json
package.json
src/components/Footer.tsx
src/components/reconocimientodevoz.tsx

[+] ✔️ Corrección Footer
[+] 🎤 Integración espectro + reconocimiento de voz

Cambios al footer + Integracion Voz

---

src/interfaces/Marcador.ts
src/screens/marcadores/AgregarMarcador.module.css
src/screens/marcadores/AgregarMarcador.tsx
src/screens/marcadores/EditarLocacion.module.css
src/screens/marcadores/EditarLocacion.tsx
src/screens/marcadores/InfoDetallada.module.css
src/screens/marcadores/InfoDetallada.tsx

El agregar marcador esta funcionando, mientras que infodetallado y editar están estáticos

Se completaron los campos solicitados

---

src/screens/resenas/Inspeccionar_Resenas.tsx

Se borraron datos predeterminados en variables y funciona la conexion a base de datos correctamente se pueden visualizar los nombres de usuarios que hicieron la reseña, calificación y comentario.

Inspeccionar reseñas conectado a SupaBase

---

src/screens/resenas/Inspeccionar_Resenas.tsx

Reverts cortesantonio/MapaInteractivo#30

Revert "Inspeccionar reseñas conectado a SupaBase"

---

src/screens/marcadores/InfoDetallada.tsx
src/screens/marcadores/css/InfoDetallada.module.css

el diseño esta listo, se logro hacer que muestre la información respectiva, Tanto desde el Marcador y las accesibilidades que se encuentran asociadas a este, (solo hay que modificar el useEffect para que tome el id desde la vista de gestión de marcadores,), de momento se debe de ingresar el id de forma manual

Esta lista la vista de la información detallada

---

src/screens/Login/loginUsuario.tsx
src/screens/accesibilidades/List.tsx
src/screens/marcadores/List.tsx
src/screens/resenas/Gestion_Resenas.tsx
src/screens/solicitudes/List.tsx
src/screens/tipoRecinto/List.tsx
src/screens/usuarios/Gestion_Usuarios.tsx

[+] Botón provisorio de volver atrás de los que faltaban

Boton provisorio volver atras

---

src/App.tsx
src/screens/marcadores/EditarLocacion.tsx
src/screens/marcadores/InfoDetallada.tsx
src/screens/marcadores/css/EditarLocacion.module.css
src/screens/marcadores/css/InfoDetallada.module.css
src/screens/resenas/css/Inspeccionar_Resenas.css

se modificaron los archivos de editar, infoDettallada y del App, se conectan con los id de los marcadores de forma dinamica mediante el url, todo funciona correctamente

Se completaron los cambios que se solicitaban y sus diseños

---

src/screens/resenas/Inspeccionar_Resenas.tsx

Ahora cuando no existen reseñas dentro de un marcador en especifico muestra una etiqueta <p>No hay Reseñas aún</p> y esto lo verifica mediante setLoading si esta es "true" esta mostrara la informacion de la reseña y si esta es false mostrara que no hay reseñas aún.

Se agrego verificador de Reseñas mediante useState.

---

src/components/Map.tsx
src/components/grafico/graficotorta.tsx
src/screens/Home.tsx
src/screens/vistaAdministrador/VistaAdministrador.tsx

[+] Se habilito los botones de StreetView + de Zoom
[+] Se incorporo localización de GPS
[+] Se arreglo css de vista administrador

Se agrego boton de zoom y Streeview + otras cosas.

---

src/components/Footer/Footer.tsx
src/components/Footer/TrazadoRuta.tsx
src/screens/Home.tsx

Esta característica ya se encuentra funcional, solo queda la terea de la imagen

La funcionalidad de Destinos recientes se conecta con el marcador

---

src/components/Footer/TrazadoRuta.tsx
src/components/VerMarcador.tsx
src/interfaces/Marcador.ts
src/screens/marcadores/AgregarMarcador.tsx
src/screens/marcadores/EditarLocacion.tsx
src/screens/marcadores/InfoDetallada.tsx

Se ingreso un campo en la interface del marcador para que la imagen se cargue de forma dinámica en los otros campos relacionados con el marcador

La característica de la imagen

---

src/screens/accesibilidades/List.tsx
src/screens/accesibilidades/css/List.module.css
src/screens/marcadores/List.tsx
src/screens/marcadores/css/List.module.css
src/screens/resenas/Gestion_Resenas.tsx
src/screens/resenas/Inspeccionar_Resenas.tsx
src/screens/resenas/css/Gestion_Resenas.module.css
src/screens/solicitudes/List.module.css
src/screens/solicitudes/List.tsx
src/screens/tipoRecinto/List.tsx
src/screens/tipoRecinto/css/List.module.css

Todos archivos de gestión se encuentran organizados mediante wrap

Se realizaron los Cambios en diferentes Archivos

---

src/components/Footer/Footer.tsx
src/components/Footer/TrazadoRuta.tsx
src/components/Footer/css/TrazadoRuta.module.css
src/components/Map.tsx
src/components/VerMarcador.tsx
src/components/grafico/graficotorta.tsx
src/screens/Home.tsx
src/screens/solicitudes/Ver.module.css

[+] Se agrego funcionalidad con ruta
[+] Se corrigieron algunos CSS

Se agrego funcionalidad con ubicacion y otras cosas

---

src/screens/usuarios/Editar_Usuarios.tsx
src/screens/usuarios/Gestion_Usuarios.tsx
src/screens/usuarios/css/Gestion_Usuarios.module.css

La jerarquía funciona se cumple la funcionalidad de los roles

La funcionalidad esta completa en cuanto a la jerarquia

---

src/components/Buscador.tsx
src/components/botoneventos.tsx
src/screens/Home.tsx
src/screens/usuarios/Gestion_Usuarios.tsx
src/screens/usuarios/Perfil_Usuarios.tsx
src/screens/usuarios/css/Perfil_Usuario.module.css

[+] Cambios relacionados con el con el div de buscador y evento.
[+] Arreglos con el componente de perfil
[+] y otros arreglos

Arreglo de detalles y cambios

---

src/screens/usuarios/Editar_Usuarios.tsx
src/screens/usuarios/Perfil_Usuarios.tsx

Se ocultan los div del rol Usuario, Gestor y Administrador, cuando quieran editar su perfil, El Usuario de rol usuario puede ver su perfil sin el rol, todo funciona como corresponde

Se completaron los cambios que faltaban en los archivos

---

src/components/NavbarAdmin.tsx
src/components/css/NavbarAdmin.module.css

Accesos directos de Gestión como: Marcadores, Usuarios, Recintos y Notificaciones, de tal manera que también funciona en vista móvil.

Se modifico el NavBar para los accesos directos

---

package-lock.json
package.json
src/components/VerMarcador.tsx
src/screens/accesibilidades/Editar.tsx
src/screens/marcadores/AgregarMarcador.tsx
src/screens/marcadores/css/AgregarMarcador.module.css
src/screens/solicitudes/AgregarSolicitud.tsx
src/screens/solicitudes/Info.tsx
src/screens/tipoRecinto/Editar.tsx

[+] Se integro Autocompletado en lo que es dirección en los formularios.
[+] Se integro un mini mapa también en este mismo formulario.

Cambios con integracion Places

---

src/components/css/EscribirResena.module.css
src/screens/marcadores/EditarLocacion.tsx
src/screens/marcadores/InfoDetallada.tsx
src/screens/marcadores/List.tsx
src/screens/marcadores/css/EditarLocacion.module.css
src/screens/resenas/Gestion_Resenas.tsx

[+] se integro places en el editar marcador.
[+] se arreglo un problema de css con el filtro.
[+] se quito un css que no se ocupaba.

Integracion de places en editar marcador.

---

src/components/Footer/User.tsx
src/components/Map.tsx
src/screens/solicitudes/Info.tsx
src/screens/solicitudes/css/info.module.css

Se aplicó el hook useFontSize al componente InfoColaborar y se realizaron ajustes menores como el tamaño del texto en "Iniciar sesión".

Aplicar modo nocturno al mapa y ajustar fuentes con useFontSize. 

---

src/App.tsx
src/components/EscribirResena.tsx
src/components/NavbarAdmin.tsx
src/screens/accesibilidades/Agregar.tsx
src/screens/accesibilidades/Editar.tsx
src/screens/accesibilidades/List.tsx
src/screens/marcadores/AgregarMarcador.tsx
src/screens/marcadores/EditarLocacion.tsx
src/screens/marcadores/InfoDetallada.tsx
src/screens/registrosLogs/RegistroLogs.tsx
src/screens/registrosLogs/css/RegistrosLogs.module.css
src/screens/solicitudes/AgregarSolicitud.tsx
src/screens/solicitudes/Ver.tsx
src/screens/tipoRecinto/Agregar.tsx
src/screens/tipoRecinto/Editar.tsx
src/screens/tipoRecinto/List.tsx
src/screens/usuarios/Agregar_Usuarios.tsx
src/screens/usuarios/Editar_Usuarios.tsx
src/screens/usuarios/Gestion_Usuarios.tsx
src/screens/usuarios/Perfil_Usuarios.tsx

Los registros que realizan los usuarios se almacenan bien, la tabla es incremental, cuando llega el limite cambia a otra paginación para rellenar lo que falta, la paginación de los números inferiores es adaptable al tamaño responsivo por tanto no se excede en la mostración de números y no rompe el balance, en la tabla registra los datos de Agregar, Eliminar, Editar, Desactivar y Activar, de los campos de Usuarios, Recintos, Accesibilidades, Reseñas, Solicitudes, Marcadores.

Creación del archivo Registro y ediciones de los archivos requeridos

---

src/screens/resenas/Inspeccionar_Resenas.tsx

[+] Se agrego funcionalidad de eliminar reseña

Se agrego funcionalidad de eliminar reseña

---

src/components/EscribirResena.tsx
src/components/grafico/graficotorta.tsx
src/interfaces/Solicitudes.ts
src/screens/solicitudes/AgregarSolicitud.tsx
src/screens/solicitudes/Ver.tsx

[+] Integración mapa en solicitud.

Integracion de mapa en solicitud, entre otras.

---

src/screens/modoCompacto/Home.tsx

Pequeño Cambio para no generar conflicto con el mati

correcion de redirecion en modocompacto a colaborar

---

package-lock.json
package.json
src/components/Buscador.tsx
src/components/Footer/Microfono.tsx
src/components/Footer/TrazadoRuta.tsx
src/components/Footer/css/Microfono.module.css
src/components/Footer/css/TrazadoRuta.module.css
src/screens/marcadores/EditarLocacion.tsx

[+] Se integro funcionalidad con buscador para integrar Búsquedas recientes (Envió de datos a búsquedas).
[+] Se arreglo funcionalidad con micrófono.
[+] Se arreglo unos problemas de css en algunas partes con el modo oscuro.

Integracion funcional microfono, entre otras cosas

---

src/screens/accesibilidades/Agregar.tsx
src/screens/accesibilidades/Editar.tsx
src/screens/marcadores/AgregarMarcador.tsx
src/screens/modoCompacto/Trazado_Compacto.tsx
src/screens/tipoRecinto/Agregar.tsx
src/screens/tipoRecinto/Editar.tsx
src/screens/tipoRecinto/List.tsx
src/screens/usuarios/Agregar_Usuarios.tsx

[+] Se integro un tema de los permisos de ubicación.
[+] Se eliminaron unas líneas no funcionales.

Cambios a trazado de ruta, entre otros

---

src/components/Buscador.tsx
src/components/Footer/Microfono.tsx
src/components/Footer/css/Footer.module.css
src/screens/modoCompacto/css/Trazado_compacto.module.css

[+] Se mejoro funcionalidad de micrófono.
[+] Se cambio el z-index del footer.
[+] Se arreglo los filtros de accesibilidad por categoría en buscador.
[+] Cambio de css en trazado de ruta modo compacto.

Se mejoro funcionalidad de micrófono

---

src/screens/modoCompacto/Home.tsx
src/screens/modoCompacto/css/Boton_Eventos.css
src/screens/modoCompacto/css/Modo_Compacto.module.css

Cambios importantes en Modo Compacto se arreglo todo el tema del scroll y se reestructuro el componente completo.

Cambios importantes en Modo Compacto se arreglo todo el tema del scroll y se reestructuro el componente completo.

---

src/screens/marcadores/EditarLocacion.tsx
src/screens/marcadores/InfoDetallada.tsx
src/screens/marcadores/css/EditarLocacion.module.css
src/screens/marcadores/css/InfoDetallada.module.css

de info detallada y edición locación

Se realizaron los puntos de diseño.

---

src/screens/horarios/Ver.tsx
src/screens/horarios/css/Ver.module.css

En Gestión de horarios del marcador

Se acaban de añadir un diseño mas representativo

---

src/screens/accesibilidades/Editar.tsx
src/screens/accesibilidades/css/Agregar.module.css
src/screens/horarios/css/Ver.module.css
src/screens/marcadores/css/InfoDetallada.module.css
src/screens/tipoRecinto/Editar.tsx
src/screens/tipoRecinto/css/Agregar.module.css

Mejor visualización en tema de organización, y arreglo datos responsivos

Se realizo la actualización en los archivos solo en tema de diseño

---

src/screens/accesibilidades/Agregar.tsx
src/screens/accesibilidades/css/Agregar.module.css
src/screens/tipoRecinto/List.tsx

En el archivo tipo recinto se corrigió el acento, mientras que en el agregado de accesibilidad se añadió las categorías en vista de referencia con información, para que los usuario sepan a que categoría debería de identificar, para añadir acc. sin problemas.

se agrego información descriptiva de las categorías que existen en accesibilidad, y correcciones varias de texto. 

---

src/screens/marcadores/AgregarMarcador.tsx

Contador de caracteres en información adicional y maxlenght para limitar la cantidad de caracteres.

Contador de caracteres en informacion adicional y maxlenght para limitar la cantidad de caracteres.

---

src/screens/solicitudes/AgregarSolicitud.tsx

Además, se modifica el botón de retroceder de position: absolute a position: static para evitar que se desplace al hacer scroll.

Cambio de input a TextArea para el envío de mensajes al colaborar.

---

src/components/botoneventos.tsx

[+] Se Mejoro el diseño de evento para una mejor visualización.

Mejora en diseño de evento.

---

src/components/Compartir.tsx
src/components/EscribirResena.tsx
src/components/Footer/Microfono.tsx
src/components/Footer/Modificador_Letras.tsx
src/components/Footer/Modo_Nocturno.tsx
src/components/Footer/TrazadoRuta.tsx
src/components/VerMarcador.tsx

se revisaron todos los archivos que se encuentran en la carpeta de componentes

Revisión ortográfica de toda la carpeta componentes

---

src/screens/marcadores/AgregarMarcador.tsx
src/screens/marcadores/EditarLocacion.tsx
src/screens/marcadores/InfoDetallada.tsx
src/screens/solicitudes/AgregarSolicitud.tsx

Mejorada la redacción de títulos y etiquetas en las vistas de "Colaborar" y otras para una mejor comprensión del contenido

Mejorada la redacción de títulos y etiquetas en las vistas de "Colaborar" y otras para una mejor comprensión del contenido

---

src/screens/marcadores/AgregarMarcador.tsx
src/screens/marcadores/EditarLocacion.tsx
src/screens/marcadores/InfoDetallada.tsx
src/screens/marcadores/List.tsx
src/screens/solicitudes/AgregarSolicitud.tsx
src/screens/solicitudes/Info.tsx
src/screens/solicitudes/List.tsx
src/screens/solicitudes/Ver.tsx
src/screens/solicitudes/css/AgregarSolicitud.module.css

Se revisaron los 2 últimos archivos, tanto la carpeta de solicitud y marcadores, se modifico el textarea, para que se mostrará el contenedor en largura en height: 100px, además de centrar el texto y se visualizara el cursor de texto '|', ya que este se encontraba pegado al borde, esto se realizo tanto en AgregarSolicitud y AgregarMarcador, con esto se finaliza la revisión ortográfica.

Finalización de revisión de ortografía de 2 archivos
